import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s - Celestique Echelon",
    default: "Welcome to - Celestique Echelon",
  },
  description: "Generated by JianWei.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-dvw relative`}
      >
        <section className="fixed top-0 left-0 w-full z-1">
          <Navigation />
        </section>
        <main className="max-w-[100dvw]">{children}</main>
      </body>
    </html>
  );
}
